version: "3"

services:

  web:
    container_name: node
    build: .
    image: florinutz:jodel_web
    ports:
      - "3000:80"
    volumes:
      - "./app:/src/app"
    links:
      - mongo
      - redis

  mongo:
    image: mongo
    volumes:
      - db-data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:4-alpine
    ports:
      - "6379"

volumes:
  db-data:
